import type { FluidUniforms } from './types'; 

export const FLUID_UNIFORM_STRUCT = /* wgsl */ `
struct U {
    x: f32,
    y: f32,
    z: f32,
    ux: u32,
    uy: u32,
    uz: u32,
    dx: f32,
    rdx: f32,
    pressureDecay: f32,
    vorticity: f32,
    dt: f32,
    t: f32,
    mouseStartX: f32,
    mouseStartY: f32,
    mouseEndX: f32,
    mouseEndY: f32,
    brushSmokeAmount: f32,
    brushFuelAmount: f32,
    smokeDecay: f32,
    temperatureDecay: f32,
    ignitionTemperature: f32,
    burnRate: f32,
    burnHeatEmit: f32,
    burnSmokeEmit: f32,
    smokeR: f32,
    smokeG: f32,
    smokeB: f32,
    boyancy: f32,
    brushVelocityAmount: f32,
    brushSize: f32,
    velocityDecay: f32,
    canvasX: f32,
    canvasY: f32,
    canvasiX: i32,
    canvasiY: i32,
    camPosX: f32,
    camPosY: f32,
    camPosZ: f32,
    stepLength: f32,
    enclosed: u32,
    emitterR: f32,
    emitterG: f32,
    emitterB: f32,
    blackbodyBrightness: f32,
    brushTemperatureAmount: f32,
    orthoBlend: f32,
    glowRadius: i32,
    glowStrength: f32,
    glowGamma: f32,
};
`

export type FluidUniformData = FluidUniforms

